### ISSUE TITLE
[mjd] Day 1 -  4장: 변수, 5장: 표현식과 문

### ISSUE THREAD

**Issue by mozzi34** [only-death/Book#1]
## 김효인
호이스팅과 일시적 사각지대(TDZ)란?

## 이율리 
![image](https://github.com/user-attachments/assets/770c5760-dad2-40f4-8ec6-ae6c42eb60c4)

## 김민서

**Comment by mozzi34** [comment]
1. 이슈사항 몬데요
2. 이수...?

**Comment by yoorli** [comment]
1. 이거슨 내가 정리한 답변들이다
2. ㅁㄴㅇ
3.

**Comment by mjpark-k** [comment]
```js
// 1번
var score = 80;

// 2번
var score = 80;
score = 90;
```
재할당인 것을 고르시오

**Comment by mozzi34** [comment]
> ```js
> // 1번
> var score = 80;
> 
> // 2번
> var score = 80;
> score = 90;
> ```
> 
> 재할당인 것을 고르시오

**Comment by mozzi34** [comment]
> ```js
> // 1번
> var score = 80;
> 
> // 2번
> var score = 80;
> score = 90;
> ```
> 
> 재할당인 것을 고르시오

2번

**Comment by mjpark-k** [comment]
1. 인터프리터가 코드를 실행하기 전에 함수, 변수 또는 임포트의 선언문을 해당
2. 변수는 하나의 값을 저장하기 위해 확보한 메모리 공간 자체이기에, 변수를 통해 값을 안전하게 접근할 수 있으며 재사용이 가능해지기 때문이다.
3. 1번, 2번
