### ISSUE TITLE
[mjd] Day 2 -  6장: 데이터 타입

### ISSUE THREAD

**Issue by mozzi34** [only-death/Book#2]
## 김효인
- symbol이 뭐예요...?

## 이율리 
질문이 따로 없어 기술면접에 나올만한 내용 공유합니다. 
데이터 타입이 왜 중요한가? 데이터 타입이 없다면 어떤 문제가 발생할 수 있을까?
원시 타입과 객체 타입의 가장 큰 차이점은 무엇인가?
자바스크립트에서 typeof 연산자는 어떤 값을 반환하나?

## 김민서

**Comment by mozzi34** [comment]
📝 [mjd] 06데이터타입 / - / 72p

**Comment by yoorli** [comment]
## 문제 1



## 문제 2

**Comment by mozzi34** [comment]
## 문제 1



## 문제 2

**Comment by claudia99503** [comment]
## 문제 1. 
다음 중 자바스크립트에서 typeof null의 결과는 무엇인가요?
a) "null"
b) "undefined"
c) "object"
d) "number"

## 문제 2.
다음 코드에서 x의 값은 무엇인가요?
```
var x = 1 + '1';
```
a) 2
b) "11"
c) 1
d) "2"

**Comment by mjpark-k** [comment]
## 문제 1.  데이터 타입이 필요한 이유를 2가지 이상 작성하세요.



## 문제 2. 변수는 타입이 있다 (O, X)

**Comment by mjpark-k** [comment]
## 자바스크립트에서 숫자 1은 항상 숫자(Number) 타입으로 간주되나요?
String 타입도 될 수 있습니다.
## 다음 코드를 실행했을 때 결과는 무엇인가요?
```
true
Infinity
number
```
## 자바스크립트에서 null과 undefined가 == 연산자로 비교될 때 결과는 무엇인가요?
==일 때는 true, === 일 때는 false
## 자바스크립트에서 false로 평가되는 값들(Falsy 값)은 무엇이 있나요?
0, undefined, '', null, NaN 등등
## 다음 중 자바스크립트에서 typeof null의 결과는 무엇인가요?
c) object
## 다음 코드에서 x의 값은 무엇인가요?
b) '11'
## 데이터 타입이 필요한 이유를 2가지 이상 작성하세요.
  - 값을 저장할 때 확보해야 하는 **메모리 공간의 크기**를 결정하기 위해
  - 값을 참조할 때 한 번에 읽어 들여야 할 **메모리 공간의 크기**를 결정하기 위해
  - 메모리에서 읽어 들인 **2진수를 어떻게 해석할지 결정**하기 위해
## 변수는 타입이 있다 (O, X)
X
기본적으로 변수는 타입을 갖지 않는다. 하지만 값은 타입을 갖는다. 따라서 현재 변수에 할당되어 있는 값에 의해 변수의 타입이 동적으로 결정된다고 표현하는 것이 적절하다.

**Comment by claudia99503** [comment]
.
